# Generated by Django 2.1 on 2018-09-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('color_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('_16_code', models.CharField(max_length=100)),
            ],
        ),
    ]
