# Generated by Django 2.1 on 2018-09-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colorrun', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='_16_code',
            new_name='code',
        ),
    ]
